### ISSUE TITLE
Sparse Reward Environment?

### ISSUE THREAD

**Issue by RushToNeverLand** [YangRui2015/Sparse-Reward-Algorithms#1]
Why flat methods (DDPG, IL, HER) perform so well on sparse reward environment? What's the sparse reward env in your experiment? What your Hierarchical DDPG, is it HAC or HIRO?

**Comment by YangRui2015** [comment]
> Why flat methods (DDPG, IL, HER) perform so well on sparse reward environment? What's the sparse reward env in your experiment? What your Hierarchical DDPG, is it HAC or HIRO?

Hello.
1) DDPG perform badly in my experiments, which you can see in the figure. Imitation learning utilizes expert experiences for accelerating training while HER uses 'relabeling' methods for data augmentation. The IL and HER methods can improve RL's performance as many works have discussed (https://arxiv.org/pdf/1709.10089.pdf, https://arxiv.org/abs/1707.01495)
2) The environment used here is FetchReach in OpenAI Gym. 
3) Hierarchical DDPG is like HAC, but without HER.

**Comment by RushToNeverLand** [comment]
well, in my opinion, the env where Agent only receives non-zero reward when achieves success can be called Sparse Reward. = =

**Comment by YangRui2015** [comment]
> well, in my opinion, the env where Agent only receives non-zero reward when achieves success can be called Sparse Reward. = =

Emm, actually in many papers such as https://arxiv.org/abs/1707.01495, the rewards are set as -1/0, where 0 represents success. Maybe sparse reward is defined as 'low probability for success'.

**Comment by RushToNeverLand** [comment]
Thank you for your reply. = =
